name: hello_world_2_github_actions

on: [push, pull_request]

# Variables d'environnement globales
env: 
  PUSH_REQUEST_MESSAGE: It's a push!
  PULL_REQUEST_MESSAGE: It's a pull!

jobs:
  push_request:
    runs-on: ubuntu-latest
    steps:
      # "actions/checkout@v3" : nécessaire lorsque'on doit analyser du code que l'on veut envoyer vers une branche GitHub. Sinon, n'est pas nécessaire pour les autres actions (workflow basé sur un event GitHub, sur un autre workflow...)
      - uses: actions/checkout@v3
      - name: 'Push request'
        # if: ${{ github.event_name == 'push' }}
        # Condition n'est ici pas obligatoire, on passe obligatoirement par un push 
        run: echo $PUSH_REQUEST_MESSAGE
  
  pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Pull request'
        run: echo $PULL_REQUEST_MESSAGE