name: hello_world_github_actions
on: push
jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: echo hello world